### ISSUE TITLE
When a new user is added to an issue via submit page on the email send say about the new user

### ISSUE THREAD

**Issue by ctranoris** [sensecitycode/sensecity-web#193]
The comment should say:
"A new user is interested in this issue and is added to the list of watchers"

**Comment by ctranoris** [comment]
The email cannot be on the comment, because then it will be public

**Comment by apalladinos** [comment]
blocked by https://github.com/sensecitycode/sensecity-api

**Comment by ctranoris** [comment]
blocked by https://github.com/sensecitycode/sensecity-api/issues/50

**Comment by ctranoris** [comment]
this is fixed due to https://github.com/sensecitycode/sensecity-api/issues/50
