### ISSUE TITLE
enhancements in admin Issue view: Επίσης ενδιαφέρονται για το αίτημα

### ISSUE THREAD

**Issue by ctranoris** [sensecitycode/sensecity-web#197]
Επίσης ενδιαφέρονται για το αίτημα: Ονομα, email τηλεφωνο
other mobiles except creator:
other name except creator:

**Comment by ctranoris** [comment]
blocked by https://github.com/sensecitycode/sensecity-api/issues/36

**Comment by ctranoris** [comment]
Cannot be fixed now. Probably https://github.com/sensecitycode/sensecity-api/issues/39 can solve this

**Comment by kostistr** [comment]
Fixed
