### ISSUE TITLE
In admin an issue is displayed as in progress although it is completed

### ISSUE THREAD

**Issue by ctranoris** [sensecitycode/sensecity-web#200]
![image](https://user-images.githubusercontent.com/968506/28527201-84879d1a-7092-11e7-88be-de793d2faf19.png)

**Comment by ctranoris** [comment]
also In public  https://patras.sense.city/scissuemap.html?issue=5973e30cf511a378c505fe79
seems in_progress but seems completed?

**Comment by apalladinos** [comment]
The request "https://api.sense.city/api/1.0/admin/issue?bug_id=4868&city=patras&email=&mobile="  returns at its response "status:IN_PROGRES" although the tags on bugzilla are correct.

**Comment by ctranoris** [comment]
this is an API issue. closing
