### ISSUE TITLE
New issues to add

### ISSUE THREAD

**Issue by ctranoris** [sensecitycode/sensecity-web#7]
καταπατήσεις κοινόχρηστων
χώρων, κυρίως από καφετέριες και εστιατόρια με τραπεζοκαθίσματα, και
περιβαλλοντικά θέματα, όπως αδέσποτα ζώα και ανακύκλωση

**Comment by bakkostas** [comment]
καταπατήσεις κοινόχρηστων χώρων -> Πεζοδρομιο / Δρόμος / Πλατεία

**Comment by bakkostas** [comment]
περιβαλλοντικά θέματα -> new issue
Contains (αδέσποτα ζώα και ανακύκλωση)

**Comment by bakkostas** [comment]
Done Web & mobile
