### ISSUE TITLE
υπηρεσία του ηλεκτροφωτισμού, πεδία 

### ISSUE THREAD

**Issue by ctranoris** [sensecitycode/sensecity-web#80]
Από την υπηρεσία του ηλεκτροφωτισμού, προτείνουμε τα πεδία "Σπασμένος Βραχίωνας" & "Ανεπαρκής Φωτισμός" να αντικατασταθούν με τα πεδία "Λαμπτήρας αναβοσβήνει" & "Επέκταση Δημοτικού Φωτισμού", καθώς και να προστεθεί τα πεδίο "Τοποθέτηση Φωτιστικού Σώματος".

**Comment by bakkostas** [comment]
OK -> Mobile
Config files -> tstcity1.json, patras.json

**Comment by bakkostas** [comment]
Fixed!
