### ISSUE TITLE
ΝΑ ΠΡΟΣΤΕΘΕΙ ΤΟ ΤΜΗΜΑ ΣΧΕΔΙΑΣΜΟΥ ΜΕΛΕΤΩΝ & ΕΛΕΓΧΟΥ ΩΣ ΕΠΙΛΟΓΗ

### ISSUE THREAD

**Issue by ctranoris** [sensecitycode/sensecity-web#83]
ΣΤΗΝ ΕΝΟΤΗΤΑ ΔΙΑΧΕΙΡΙΣΗ ΤΟΥ ΑΙΤΗΜΑΤΟΣ ΝΑ ΠΡΟΣΤΕΘΕΙ ΤΟ ΤΜΗΜΑ ΣΧΕΔΙΑΣΜΟΥ ΜΕΛΕΤΩΝ & ΕΛΕΓΧΟΥ ΩΣ ΕΠΙΛΟΓΗ

**Comment by bakkostas** [comment]
Έχει σταλεί email στο gep@patr.... στις 27/01/2017 με τίτλο Ενεργά Τμήματα Δήμου Πατρέων και δεν έχει απαντηθεί!!!!
